import { defineNuxtModule, addComponent, createResolver, addTemplate, addTypeTemplate, addVitePlugin, resolveFiles, updateTemplates } from '@nuxt/kit'
import type { Config as SvgoConfig } from 'svgo'
import { relative, resolve as resolvePath } from 'node:path'
import { existsSync } from 'node:fs'

declare module 'nuxt/schema' {
  interface PublicRuntimeConfig {
    svgIcon: {
      iconsDir: string
      prefix: string
    }
  }
}

export interface ModuleOptions {
  /**
   * Directory where SVG icons are stored, relative to project root.
   * Supports glob patterns for subdirectories.
   * @default 'app/assets/icons' if the project has an `app` directory, otherwise `'assets/icons'`
   */
  iconsDir: string

  /**
   * Name of the component registered globally.
   * @default 'Icon'
   */
  componentName: string

  /**
   * Global prefix for CSS classes on the icon element.
   * @default 'icon'
   */
  prefix: string

  /**
   * Enable automatic SVG optimization via SVGO.
   * @default true
   */
  optimize: boolean

  /**
   * Custom SVGO configuration. Only used when `optimize` is true.
   * @default {}
   */
  svgoConfig: SvgoConfig
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-svg-icon-module',
    configKey: 'svgIcon',
    compatibility: {
      nuxt: '>=3.10.0',
    },
  },
  defaults: nuxt => ({
    iconsDir: existsSync(resolvePath(nuxt.options.rootDir, 'app'))
      ? 'app/assets/icons'
      : 'assets/icons',
    componentName: 'Icon',
    prefix: 'icon',
    optimize: true,
    svgoConfig: {},
  }),
  async setup(options, nuxt) {
    const { resolve } = createResolver(import.meta.url)

    // iconsDir is relative to rootDir, but Vite glob keys are relative to srcDir.
    // Strip the srcDir prefix so the runtime path matches glob keys at all times.
    const srcDirRel = relative(nuxt.options.rootDir, nuxt.options.srcDir)
    const iconsDirForGlob = srcDirRel
      ? options.iconsDir.replace(new RegExp(`^${srcDirRel}/`), '')
      : options.iconsDir

    nuxt.options.runtimeConfig.public.svgIcon = {
      iconsDir: iconsDirForGlob,
      prefix: options.prefix,
    }

    const p = options.prefix
    const css = addTemplate({
      filename: 'nuxt-svg-icon-module.css',
      write: true,
      getContents: () => `
.${p} svg { width: 1em; height: 1em; vertical-align: middle; margin-bottom: 0.03em; }
.${p}_fill, .${p}_fill * { fill: currentColor; }
.${p}_stroke, .${p}_stroke * { stroke: currentColor; }
`.trimStart(),
    })
    nuxt.options.css.push(css.dst)

    const iconsAbsDir = resolvePath(nuxt.options.rootDir, options.iconsDir)

    async function getIconNames(): Promise<string[]> {
      const files = await resolveFiles(iconsAbsDir, '**/*.svg').catch(() => [])
      return files
        .map(f => relative(iconsAbsDir, f).replace(/\.svg$/, '').replace(/\\/g, '/'))
        .sort()
    }

    const iconTypeTemplate = addTypeTemplate({
      filename: 'types/nuxt-svg-icon-module.d.ts',
      getContents: async () => {
        const names = await getIconNames()
        const union = names.length ? names.map(n => JSON.stringify(n)).join(' | ') : 'string'
        const componentName = options.componentName
        return [
          `// Generated by nuxt-svg-icon-module`,
          `export type IconName = ${union}`,
          `declare module 'vue' {`,
          `  interface GlobalComponents {`,
          `    ${componentName}: import('vue').DefineComponent<{ name: IconName; filled?: boolean; label?: string }, {}, {}>`,
          `    Lazy${componentName}: import('vue').DefineComponent<{ name: IconName; filled?: boolean; label?: string }, {}, {}>`,
          `  }`,
          `}`,
          `declare module 'nuxt-svg-icon-module' {`,
          `  export type { IconName }`,
          `}`,
        ].join('\n') + '\n'
      },
    })

    nuxt.options.alias['nuxt-svg-icon-module'] = iconTypeTemplate.dst

    addVitePlugin(virtualIconModule())

    addComponent({
      name: options.componentName,
      filePath: resolve('./runtime/components/Icon.vue'),
    })

    nuxt.hook('builder:watch', async (event, watchPath) => {
      const absPath = resolvePath(nuxt.options.rootDir, watchPath)
      if (!absPath.startsWith(iconsAbsDir) || !watchPath.endsWith('.svg')) return
      await updateTemplates({ filter: t => t.filename === iconTypeTemplate.filename })
    })

    if (options.optimize) {
      addVitePlugin(svgOptimizePlugin(options.svgoConfig))
    }
  },
})

function virtualIconModule() {
  const VIRTUAL_ID = 'nuxt-svg-icon-module'
  const RESOLVED_ID = '\0' + VIRTUAL_ID
  return {
    name: 'nuxt-svg-icon:virtual-module',
    resolveId(id: string) {
      if (id === VIRTUAL_ID) return RESOLVED_ID
    },
    load(id: string) {
      if (id === RESOLVED_ID) return `export {}`
    },
  }
}

function svgOptimizePlugin(svgoConfig: SvgoConfig) {
  return {
    name: 'nuxt-svg-icon:optimize',
    enforce: 'pre' as const,
    async load(filePath: string) {
      const [path, query] = filePath.split('?')
      if (!path.endsWith('.svg') || query !== 'raw') return

      const { readFile } = await import('node:fs/promises')
      const { optimize } = await import('svgo')

      const raw = await readFile(path, 'utf8')
      const result = optimize(raw, svgoConfig)
      return `export default ${JSON.stringify(result.data)}`
    },
  }
}
